<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/camila_araujo/aula_14.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [3]:
bmi > 23

array([False, False, False,  True, False])

In [4]:
bmi[bmi > 23]

array([24.7473475])

In [5]:
peso = 90
altura = 1.65

bmi = peso / (altura ** 2)

if bmi > 30:
    print("Você está com sobrepeso")
else:
    print("Você está com peso adequado")


Você está com sobrepeso


In [6]:
import numpy as np

bmi = np.array([22.5, 27.8, 31.2, 18.4, 24.0])

resposta = bmi < 23

print(resposta)


[ True False False  True False]


pratique 143

In [7]:
print(True == False)
print(-5 * 15 == 75)
print("pyscript" == "PyScript")
print(True == 1)


False
False
False
True


pratique 144

In [9]:
import numpy as np
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

print(my_house > 18)

print(my_house < your_house)


[False  True False False]
[False  True  True False]


pratique 150


In [11]:
my_kitchen = 18.0
your_kitchen = 14.0

print(my_kitchen > 10 and my_kitchen < 18)
print(my_kitchen < 14 and my_kitchen < 17)
print(2 * my_kitchen < 3 * your_kitchen)


False
False
True


pratique 151

In [13]:
import numpy as np

my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

print((my_house > 18.5) | (my_house < 10))

print((my_house < 11) & (your_house < 11))




[False  True False  True]
[False False False  True]
