<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/camila_araujo/aula_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
z = 4
if 2 % 2 == 0:
  print('z is even')

Z is even


In [ ]:
z = 5
if z % 2 == 0:
  print('checking' + str(z))
  print('z is even')

In [ ]:
z = 5
if z % 2 == 0:
  print('z is even')
else:
  print('z is odd')

z is odd


In [ ]:
z = 3
if z % 2 == 0:
  print('z is divisible by 2')
elif z % 3 == 0:
  print('z is divisible by 3')
else:
  print('z is divisible by 2 nor by 3')

z is divisible by 3


pratique 156

In [ ]:
room = 'kit'
area = 14.0

if room == 'kit':
    print('Looking around in the kitchen.')
    if area > 15:
        print('Big Place')
    else:
        print('Pretty small')


Looking around in the kitchen.
Pretty small


filtragem de elementos com pandas

In [ ]:
import pandas as pd
brics = pd.read_csv('https://drive.usercontent.google.com/download?id=1AyKIujQCftGvsAZRMjrHBj8pSXPAzRq_&export=download&authuser=1', index_col=0)
brics

country    capital    area  population
country_ab                                             
BR                Brazil   Brasilia   8.516      200.40
RU                Russia     Moscow  17.100      143.50
IN                 India  New Delhi   3.286     1252.00
CH                 China    Beijing   9.597     1357.00
SA          South Africa   Pretoria   1.221       52.98

In [11]:
brics['area']

country_ab
BR     8.516
RU    17.100
IN     3.286
CH     9.597
SA     1.221
Name: area, dtype: float64

In [12]:
brics ['area'] > 8

country_ab
BR     True
RU     True
IN    False
CH     True
SA    False
Name: area, dtype: bool

In [15]:
brics[brics['area'] > 8]

country   capital    area  population
country_ab                                      
BR          Brazil  Brasilia   8.516       200.4
RU          Russia    Moscow  17.100       143.5
CH           China   Beijing   9.597      1357.0

pratique 162

In [18]:
import pandas as pd

brics = pd.read_csv('https://drive.usercontent.google.com/download?id=1kp1WzC5JojaWuj_HuSWni61Upsa1N9bo&export=download&authuser=1', index_col = 0)
dr = brics["drives_right"] == True
sel = brics[dr]
print(sel)

print(brics[brics["drives_right"] == True])


            cars_per_cap        country  drives_right
country_ab                                           
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True
            cars_per_cap        country  drives_right
country_ab                                           
US                   809  United States          True
RU                   200         Russia          True
MOR                   70        Morocco          True
EG                    45          Egypt          True


In [21]:
error = 50.0
while error > 1:
  error = error / 4
  print(error)

12.5
3.125
0.78125


pratique 164

In [24]:
offset = 10

while offset != 0:
    offset -= 1
    print(offset)


9
8
7
6
5
4
3
2
1
0


In [26]:
fam = [1.73, 1.68, 1.71, 1.89]
for height in fam:
  print(height)

1.73
1.68
1.71
1.89


In [27]:
fam = [1.73, 1.68, 1.71, 1.89]
for index, height in enumerate(fam):
  print('index' + str(index) + ': ' + str(height))

index0: 1.73
index1: 1.68
index2: 1.71
index3: 1.89


pratique 167

In [28]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

for area in areas:
    print(area)


11.25
18.0
20.0
10.75
9.5


pratique 168

In [29]:
areas = [11.25, 18.0, 20.0, 10.75, 9.50]

for index, area in enumerate(areas):
    print(f"Index {index}: {area}")



Index 0: 11.25
Index 1: 18.0
Index 2: 20.0
Index 3: 10.75
Index 4: 9.5


pratique 169

In [3]:
house  = [['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.50]]

for room in house:
    name = room[0]
    area = room[1]
    print(f"The {name} is {area} sqm")


The hallway is 11.25 sqm
The kitchen is 18.0 sqm
The living room is 20.0 sqm
The bedroom is 10.75 sqm
The bathroom is 9.5 sqm


In [8]:
world = {'afghanisthan': 30.55,
        'albania': 2.77,
        'algeria': 39.21}

for key, value in world.items():
   print(key + '--' + str(value))

afghanisthan--30.55
albania--2.77
algeria--39.21


In [9]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = np_weight / np_height ** 2
for val in bmi:
  print(val)

21.85171572722109
20.97505668934241
21.750282138093777
24.74734749867025
21.44127836209856


In [11]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas = np.array([np_height, np_weight])
for val in meas:
  print(val)

[1.73 1.68 1.71 1.89 1.79]
[65.4 59.2 63.6 88.4 68.7]


In [12]:
import numpy as np
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])
np_weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
meas = np.array([np_height, np_weight])
for val in np.nditer(meas):
  print(val)

1.73
1.68
1.71
1.89
1.79
65.4
59.2
63.6
88.4
68.7


pratique 175

In [13]:
europe = {
    'spain': 'madrid',
    'france': 'paris',
    'germany': 'berlin',
    'norway': 'oslo',
    'italy': 'rome',
    'poland': 'warsaw',
    'austria': 'vienna'
}

for country, capital in europe.items():
    print(f"The capital of {country} is {capital}")


The capital of spain is madrid
The capital of france is paris
The capital of germany is berlin
The capital of norway is oslo
The capital of italy is rome
The capital of poland is warsaw
The capital of austria is vienna


pratique 176

In [14]:
import numpy as np

array_2d = np.array([
    np.arange(1, 11),
    np.arange(11, 21)])

for linha in array_2d:
    print(linha)

for linha in array_2d:
    for elemento in linha:
        print(elemento)


[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [21]:
import pandas as pd
brics = pd.read_csv('https://drive.usercontent.google.com/download?id=1kp1WzC5JojaWuj_HuSWni61Upsa1N9bo&export=download&authuser=1', index_col = 0)
for val in brics:
  print(val)

cars_per_cap
country
drives_right


In [22]:
import pandas as pd
brics = pd.read_csv('https://drive.usercontent.google.com/download?id=1kp1WzC5JojaWuj_HuSWni61Upsa1N9bo&export=download&authuser=1', index_col = 0)
for lab, row in brics.iterrows():
  print(lab)
  print(row)


US
cars_per_cap              809
country         United States
drives_right             True
Name: US, dtype: object
AUS
cars_per_cap          731
country         Australia
drives_right        False
Name: AUS, dtype: object
JAP
cars_per_cap      588
country         Japan
drives_right    False
Name: JAP, dtype: object
IN
cars_per_cap       18
country         India
drives_right    False
Name: IN, dtype: object
RU
cars_per_cap       200
country         Russia
drives_right      True
Name: RU, dtype: object
MOR
cars_per_cap         70
country         Morocco
drives_right       True
Name: MOR, dtype: object
EG
cars_per_cap       45
country         Egypt
drives_right     True
Name: EG, dtype: object


In [24]:
import pandas as pd
brics = pd.read_csv('https://drive.usercontent.google.com/download?id=1kp1WzC5JojaWuj_HuSWni61Upsa1N9bo&export=download&authuser=1', index_col = 0)
for lab, row in brics.iterrows():
  print(lab + ': ' + row['country'])

US: United States
AUS: Australia
JAP: Japan
IN: India
RU: Russia
MOR: Morocco
EG: Egypt


In [25]:
import pandas as pd
brics = pd.read_csv('https://drive.usercontent.google.com/download?id=1kp1WzC5JojaWuj_HuSWni61Upsa1N9bo&export=download&authuser=1', index_col = 0)
for lab, row in brics.iterrows():
  brics.loc[lab, 'name_length'] = len(row['country'])
  print(brics)

            cars_per_cap        country  drives_right  name_length
country_ab                                                        
US                   809  United States          True         13.0
AUS                  731      Australia         False          NaN
JAP                  588          Japan         False          NaN
IN                    18          India         False          NaN
RU                   200         Russia          True          NaN
MOR                   70        Morocco          True          NaN
EG                    45          Egypt          True          NaN
            cars_per_cap        country  drives_right  name_length
country_ab                                                        
US                   809  United States          True         13.0
AUS                  731      Australia         False          9.0
JAP                  588          Japan         False          NaN
IN                    18          India         False         

In [26]:
import pandas as pd
brics = pd.read_csv('https://drive.usercontent.google.com/download?id=1kp1WzC5JojaWuj_HuSWni61Upsa1N9bo&export=download&authuser=1', index_col = 0)
for lab, row in brics.iterrows():
  brics['name_length'] = brics['country'].apply(len)
  print(brics)

            cars_per_cap        country  drives_right  name_length
country_ab                                                        
US                   809  United States          True           13
AUS                  731      Australia         False            9
JAP                  588          Japan         False            5
IN                    18          India         False            5
RU                   200         Russia          True            6
MOR                   70        Morocco          True            7
EG                    45          Egypt          True            5
            cars_per_cap        country  drives_right  name_length
country_ab                                                        
US                   809  United States          True           13
AUS                  731      Australia         False            9
JAP                  588          Japan         False            5
IN                    18          India         False         

pratique 182

In [36]:
import pandas as pd
cars = pd.read_csv('https://drive.usercontent.google.com/download?id=1kp1WzC5JojaWuj_HuSWni61Upsa1N9bo&export=download&authuser=1', index_col = 0)

for index, row in cars.iterrows():
    print(f"Linha ID {index}:")
    print(row)


Linha ID US:
cars_per_cap              809
country         United States
drives_right             True
Name: US, dtype: object
Linha ID AUS:
cars_per_cap          731
country         Australia
drives_right        False
Name: AUS, dtype: object
Linha ID JAP:
cars_per_cap      588
country         Japan
drives_right    False
Name: JAP, dtype: object
Linha ID IN:
cars_per_cap       18
country         India
drives_right    False
Name: IN, dtype: object
Linha ID RU:
cars_per_cap       200
country         Russia
drives_right      True
Name: RU, dtype: object
Linha ID MOR:
cars_per_cap         70
country         Morocco
drives_right       True
Name: MOR, dtype: object
Linha ID EG:
cars_per_cap       45
country         Egypt
drives_right     True
Name: EG, dtype: object


pratique 183

In [35]:
import pandas as pd

brics = pd.read_csv('https://drive.usercontent.google.com/download?id=1kp1WzC5JojaWuj_HuSWni61Upsa1N9bo&export=download&authuser=1', index_col=0)

print(brics.columns)

for lab, row in brics.iterrows():
    print(f"{lab}: {row['cars_per_cap']}")


Index(['cars_per_cap', 'country', 'drives_right'], dtype='object')
US: 809
AUS: 731
JAP: 588
IN: 18
RU: 200
MOR: 70
EG: 45


pratique 184

In [37]:
import pandas as pd
cars = pd.read_csv('https://drive.usercontent.google.com/download?id=1kp1WzC5JojaWuj_HuSWni61Upsa1N9bo&export=download&authuser=1', index_col=0)

country_names = []

for label, row in cars.iterrows():
    country_names.append(label.upper())

cars["COUNTRY"] = country_names

print(cars)


            cars_per_cap        country  drives_right COUNTRY
country_ab                                                   
US                   809  United States          True      US
AUS                  731      Australia         False     AUS
JAP                  588          Japan         False     JAP
IN                    18          India         False      IN
RU                   200         Russia          True      RU
MOR                   70        Morocco          True     MOR
EG                    45          Egypt          True      EG


pratique 185

In [39]:
import pandas as pd
cars = pd.read_csv('https://drive.usercontent.google.com/download?id=1kp1WzC5JojaWuj_HuSWni61Upsa1N9bo&export=download&authuser=1', index_col=0)

cars['country'] = cars['country'].apply(str.upper)

print(cars)

            cars_per_cap        country  drives_right
country_ab                                           
US                   809  UNITED STATES          True
AUS                  731      AUSTRALIA         False
JAP                  588          JAPAN         False
IN                    18          INDIA         False
RU                   200         RUSSIA          True
MOR                   70        MOROCCO          True
EG                    45          EGYPT          True


In [40]:
import numpy as np
np.random.rand()

0.6899391990076632

In [41]:
np.random.seed(123)
np.random.rand()

0.6964691855978616

In [42]:
np.random.rand()

0.28613933495037946

In [43]:
import numpy as np
np.random.seed(123)
coin = np.random.randint(0,2)
print(coin)

0


In [44]:
import numpy as np
np.random.seed(123)
coin = np.random.randint(0,2)
print(coin)
if coin == 0:
  print('heads')
else:
  print('tails')

0
heads


In [45]:
def soma(n1, n2):
  print('soma: ', n1+n2)
soma(4,5)

soma:  9


In [48]:
def soma(n1, n2):
  return n1+n2
print('soma: ', soma(4,5))

soma:  9


In [49]:
def is_par(n):
  if n % 2 == 0:
    return True
  else:
    return False
print(is_par(4))

True


pratique 203

In [51]:
def soma(a, b):
    return a + b

def subtracao(a, b):
    return a - b

def multiplicacao(a, b):
    return a * b

def divisao(a, b):
    if b != 0:
        return a / b
    else:
        return "Erro: divisão por zero"

x = 10
y = 2

print(f"Soma: {x} + {y} = {soma(x, y)}")
print(f"Subtração: {x} - {y} = {subtracao(x, y)}")
print(f"Multiplicação: {x} * {y} = {multiplicacao(x, y)}")
print(f"Divisão: {x} / {y} = {divisao(x, y)}")


Soma: 10 + 2 = 12
Subtração: 10 - 2 = 8
Multiplicação: 10 * 2 = 20
Divisão: 10 / 2 = 5.0
