<a href="https://colab.research.google.com/github/alysonbz/lab_prog_si/blob/camila_araujo/aula8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Pagina 68

In [ ]:
import random as rd
import numpy as np

height = range(150,210)

weight = range(50,149)

height = rd.sample(height,20)

weight = rd.sample(weight,20)

height_array = np.array(height) * 0.01

weight_array = np.array(weight)

bmi = weight_array / height_array **2

light = bmi[bmi < 21]

print(light)

print(weight_array[8:15])

print(height_array[11:19])

[12.37593129 17.92884018 14.45936673 14.00266051]
[ 71 108  94  75 123 126  59]
[1.58 1.9  1.97 2.02 1.77 1.81 2.07 1.54]


Pagina 72

In [ ]:
baseball = [[180, 78.4],
           [215, 102.7],
           [210, 98.5],
           [188, 75.3]]

import numpy as np

np_baseball = np.array(baseball)

print(np_baseball[2, :])

np_weight_lb = np_baseball[: , 1]

print(np_baseball[1,0])

np.median(np_baseball[:, 0])



[210.   98.5]
215.0


np.float64(199.0)